### ISSUE TITLE
修正 raster-dem 圖磚來源

### ISSUE THREAD

**Issue by typebrook** [aga3134/SourcingWater#1]
https://github.com/aga3134/SourcingWater/blob/265884c9f181230c6f2dcc18cf49fcdcff2ffd29/static/js/main.js#L243-L248

Mapbox的高程模型由於不是從內政部開放資料產製，其準確性並不高。在某些地域尤其會發現明顯的不合理之處。例如花蓮的壽豐溪流域，靠近南二子山的溪床有隆起的現象：

![1](https://user-images.githubusercontent.com/19887090/140676691-890ead88-cdd8-421a-afb7-d93c53536427.png)
![2](https://user-images.githubusercontent.com/19887090/140676684-d3b1b0f7-0656-4f39-baf6-70e976e1f512.png)

@aga3134 我在 https://github.com/OsmHackTW/terrain-rgb 有發布適用於台灣的高程圖磚，可以直接使用在`addSource`中使用。另外，若覺得gh-pages的服務速度不夠快，也可以將圖磚資料集上傳至 https://studio.mapbox.com/datasets/ ，再取得url使用。

**Comment by aga3134** [comment]
感謝提供資料，我再試試。

**Comment by typebrook** [comment]
@aga3134 
照理說，應該可以直接把source 替換成：
https://osmhacktw.github.io/terrain-rgb/tiles.json
```javascript
 this.map.addSource('mapbox-dem', { 
     'type': 'raster-dem', 
     'url': 'https://osmhacktw.github.io/terrain-rgb/tiles.json', 
     'tileSize': 256, 
     'maxzoom': 12
 }); 
```

不過因為gh-pages 1GB的限制，我的圖磚解析度只有256x256，maxzoom也只到12，在表現上不知道會不會有差。你可以自己先做個比較。

**Comment by aga3134** [comment]
@typebrook v1.1.0版已使用你的高程圖磚，你可以再試試。
我這邊的測試，解析度、速度都ok，
有問題的地方是在zoom out到接近全台的時候，似乎因為超過圖磚zoom的範圍導致地形高程沒顯示，連帶造成點擊功能失效。
所以目前程式會用zoom level判斷，在小尺度時使用你的圖磚，大尺度時使用mapbox的圖磚。
